package com.springboot.domain;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_T.TEST_ID
     *
     * @mbggenerated
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_T.AA_NAME
     *
     * @mbggenerated
     */
    private String aaName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_T.TEST_ID
     *
     * @return the value of TEST_T.TEST_ID
     *
     * @mbggenerated
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_T.TEST_ID
     *
     * @param testId the value for TEST_T.TEST_ID
     *
     * @mbggenerated
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_T.AA_NAME
     *
     * @return the value of TEST_T.AA_NAME
     *
     * @mbggenerated
     */
    public String getAaName() {
        return aaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_T.AA_NAME
     *
     * @param aaName the value for TEST_T.AA_NAME
     *
     * @mbggenerated
     */
    public void setAaName(String aaName) {
        this.aaName = aaName == null ? null : aaName.trim();
    }
}