server:
  port: 80
spring:
  datasource:
    username: mwp
    password: mwp
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@144.131.254.205:1521:mwpdb
    name: test
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.springboot.domain
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-prefix: dao.

logging:
  config: classpath:logback.xml

